### ISSUE TITLE
Found incorrect type for field 'scroll' in class ChatSessionState. Expected 'Int', found __NSCFNumber instead

### ISSUE THREAD

**Issue by trevinwisaksana** [crisp-im/crisp-sdk-ios#40]
Hi,

A user has not been able to open Crisp at all and keeps getting "Error starting chat" when opening the chat. I noticed that this error below keeps showing. We are using Crisp 1.0.10. All we did from our side is upon login this user sets a token ID. The user then gets this error regardless of the device this person is using when opening the chat. Can you please fix this as soon as possible? It seems to have permanently stopped this user from using Crisp.

`[error] (Parsing) Found incorrect type for field 'scroll' in class ChatSessionState. Expected 'Int', found __NSCFNumber instead.`

![Image from iOS](https://user-images.githubusercontent.com/20000813/108660840-a9d83980-74fd-11eb-8a93-75eee423733d.png)

**Comment by nesium** [comment]
Hi @trevinwisaksana. Thanks for the report. This should hopefully be fixed in 1.0.11. Let us know if that solves your problem.

**Comment by trevinwisaksana** [comment]
Version 1.0.11 seems to fix this problem. Thanks

**Comment by baptistejamin** [comment]
:)

**Comment by StevenWatremez** [comment]
Hello, I analysed the log inside the SDK through Firebase and I saw in the version `1.6.1` that the issue is still there with a pic during the 22 of July. Do you have an idea about the pic and the issue during the other days ? 
<img width="1779" alt="Screenshot 2022-07-27 at 12 17 28" src="https://user-images.githubusercontent.com/11426754/181224493-930abff0-66e1-410f-9bcf-61607fb88c27.png">

**Comment by nesium** [comment]
Hi @StevenWatremez. Thanks for recording these!

It seems like I finally figured out the root cause and was able to reproduce it in a unit test. I'm hopeful that version 1.6.2 will fix that issue for you. Please give it a try.

Thanks!
